Add Step, ELU, SELU, Swish activation functions
ml-explore/mlx pull request #117
Opened 2023-12-10 12:03 UTC by nsantavas

This commit adds the Step, ELU, SELU and Swish activations functions

2023-12-10 15:02 UTC, awni commented
Can you rebase on https://github.com/ml-explore/mlx/pull/108/files and remove the duplicate activations?

2023-12-10 15:42 UTC, nsantavas commented
> Can you rebase on https://github.com/ml-explore/mlx/pull/108/files and remove the duplicate activations?

Done

2023-12-11 08:14 UTC, nsantavas commented
@awni rebased again to main due to conflicts

2023-12-11 16:07 UTC, m0saan commented
@nsantavas could you please add the new activation functions to the docs? https://github.com/ml-explore/mlx/blob/f4ddd7dc44aef7eb4d41b7f372d985e513ff808f/docs/src/python/nn.rst?plain=1#L161C2-L161C2

2023-12-11 16:12 UTC, nsantavas commented
> @nsantavas could you please add the new activation functions to the docs? https://github.com/ml-explore/mlx/blob/f4ddd7dc44aef7eb4d41b7f372d985e513ff808f/docs/src/python/nn.rst?plain=1#L161C2-L161C2

@m0saan done

2023-12-11 16:52 UTC, awni requested changes
Thanks for the contributions, this is looking good! A few more comments / questions.

2023-12-11 16:52 UTC, awni commented on python/tests/test_nn.py
> +        self.assertTrue(mx.array_equal(y, expected))
Use `mx.allclose` here as I've noticed exact equality sometimes fails due to subtle numerical differences.

2023-12-11 16:52 UTC, awni commented on python/tests/test_nn.py
> +        self.assertTrue(mx.array_equal(y, expected))
Same comment as above re `mx.allclose`. Also the first `array_equal` is not used, could you remove it?

2023-12-11 16:52 UTC, awni commented on python/mlx/nn/layers/activations.py
> +    return x * mx.sigmoid(x)
This is the same function as the `SiLU`. Could you remove it + the accompanying changes, and maybe just update the SiLU docstring to mention it is also known as the `swish`?

2023-12-11 16:52 UTC, awni commented on python/mlx/nn/layers/activations.py
> +    r"""Applies the Step Activation Function.
nit: lower case "Activation Function."

2023-12-11 16:52 UTC, awni commented on python/mlx/nn/layers/activations.py
> +    r"""Applies the Step Activation Function.
nit: lower case "Activation Function."

2023-12-11 16:52 UTC, awni commented on python/mlx/nn/layers/activations.py
> +def step(x: mx.array, threshold: float = 0.0):
This is a non-standard activation (given it's derivative is 0 almost everywhere). What's the motivation to include it?

2023-12-11 17:01 UTC, nsantavas commented
@awni Done

2023-12-12 01:04 UTC, awni approved these changes

2023-12-12 01:04 UTC, merged