init structure for mx.stack support
ml-explore/mlx pull request #123
Opened 2023-12-10 22:35 UTC by j-csc

TODO: 
- Finish implementation of stack
- Add test cases for 2+d stacking
- Add Python bindings 
- Figure out whether to add additional overload array types for stack / do it in Python

2023-12-12 00:05 UTC, angeloskath commented on mlx/utils.cpp
> +    return ((a.shape() == arrays[0].shape()) && a.dtype() == arrays[0].dtype());
I would change the name to `is_same_shape` and remove the dtype check which isn't in the name either.

2023-12-12 03:29 UTC, j-csc commented on mlx/ops.cpp
> +    new_arrays.emplace_back(expand_dims(a, normalized_axis, s));
made the change in concat, used `result_type`

2023-12-12 07:56 UTC, angeloskath requested changes
Thanks for the changes. It looks great. If it isn't too much trouble I will ask for a few more updates. I hope it 's ok.

- Could you rebase on top of main and run the style checks?
- Could you also implement the python bindings? It is quite a simple addition after the work you 've already done.

Thanks again!

2023-12-14 00:23 UTC, j-csc commented
pushed up the fix, lmk if there's anything else

2023-12-14 00:34 UTC, j-csc commented on python/src/ops.cpp
> +      Union[None, Stream, Device] = None) -> array
will get these fixed up

2023-12-14 00:46 UTC, angeloskath requested changes
Looks perfect. I left some style comments that currently break the docs if not updated.

Sorry for the back and forth. In the future if you want I could apply these minor changes myself and then merge. Just let me know if it is ok. I didn't do it by default cause I would show up as a co-author and steal a bit of your thunder which I didn't want.

2023-12-14 00:46 UTC, angeloskath commented on python/src/ops.cpp
> +          input arrays are stacked. Defaults to 0. stream (Stream, optional):
I am really sorry to have to do this to you again but could you fix the style here. Basically `input` should be indented and stream should be in the line below.

2023-12-14 00:46 UTC, angeloskath commented on python/src/ops.cpp
> +      Union[None, Stream, Device] = None) -> array
Same as below style change, could you put it all in one line to match the rest of the signatures? Maybe in the future we 'll enforce all of them in 80 or 120 chars but for now...

2023-12-14 00:46 UTC, angeloskath commented on python/src/ops.cpp
> +          axis 0.
Indent or even better simplify to `array: The resulting stacked array`

2023-12-14 00:52 UTC, j-csc commented
> Looks perfect. I left some style comments that currently break the docs if not updated.
> 
> Sorry for the back and forth. In the future if you want I could apply these minor changes myself and then merge. Just let me know if it is ok. I didn't do it by default cause I would show up as a co-author and steal a bit of your thunder which I didn't want.

Not at all, just happy to help! Will push up these fixes

2023-12-14 21:19 UTC, angeloskath commented
@awni waiting on your approval on this.

2023-12-14 21:20 UTC, awni approved these changes

2023-12-14 21:21 UTC, merged