Metal-cpp version bump
ml-explore/mlx pull request #1668
Opened 2024-12-07 13:02 UTC by ameszy

Apple has released the stable version of Metal-cpp for macOS 15 and iOS 18. CMakeLists.txt is updated to build with it instead of the beta one.

2024-12-07 14:18 UTC, awni approved these changes
Thanks!

2024-12-09 18:32 UTC, awni requested changes
Please run the format hooks.

2024-12-10 01:50 UTC, ameszy commented
I admit I omitted the format hooks thinking it was just a small change so probably I won't need those. I'm sorry for that and for the inconvenience caused. The new commit now includes the style fix done by those scripts.

2024-12-10 03:08 UTC, awni approved these changes
Thanks!

2024-12-10 03:40 UTC, merged