added tri / tril / triu
ml-explore/mlx pull request #170
Opened 2023-12-14 22:52 UTC by dc-dc-dc

## Proposed changes

Adding tri / tril / triu

I know there was pushback on using torch as a dependency in tests but was wondering if comparing to numpy was okay, simplifies and expands the test cases to try against vs saving expected results.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

2023-12-14 23:01 UTC, awni commented
> but was wondering if comparing to numpy was okay

Yup that's ok, we already do it in fact.

2023-12-15 01:18 UTC, dc-dc-dc commented
Cool, added some basic ctests and utilized numpy in the python tests which cover more diagonals.

2023-12-15 03:20 UTC, awni commented on mlx/ops.h
> +array tri(int n, int m, int k, Dtype type, StreamOrDevice s = {});
Can you do an overload of  `tri(int n, Dtype ...) where `m=n` and `k=0`. I think it's a common use case.

2023-12-15 03:22 UTC, awni commented on python/tests/test_ops.py
> +        nt = np.array(mt.tolist())
`.tolist` is not necesssary

2023-12-15 03:42 UTC, awni requested changes
This is really awesome, thanks for adding it! Left some comments.

2023-12-15 03:42 UTC, awni commented on python/tests/test_ops.py
> +        nt = np.array(mt.tolist())
same here.

2023-12-15 03:42 UTC, awni commented on python/tests/test_ops.py
> +
please add one or two test for `m` and `k` other than defaults.

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +        An array with zeros above the given diagonal and self elsewhere.
`self elsewhere` is odd. Maybe change this to `Zeros the array above the given diagonal.`

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +          stream (Stream, optional): Stream or device. Defaults to None.
Double back ticks on `None`

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +          array: Array filled with zeros above given diagonal
`Array zeroed above the given diagonal`

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +          array: Array filled with zeros below given diagonal
Same comments for this docstring but below instead of above.

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +      "k"_a,
Could you make these optional and follow the numpy defaults?

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +          stream (Stream, optional): Stream or device. Defaults to None.
Double backticks on `float32` and `None`.

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +      "dtype"_a = std::nullopt,
This could just default to `float32` rather than use an `optional` type. Simpler that way.

2023-12-15 03:42 UTC, awni commented on python/src/ops.cpp
> +      "dtype"_a = std::nullopt,
I should have caught that for some other ops like `eye` above. If you are up for cleaning those as well that would be nice!

2023-12-15 03:42 UTC, awni commented on mlx/ops.cpp
> +    throw std::invalid_argument("array must be atleast 2-D");
Add `[triu]` to the front of the error message.

2023-12-15 03:42 UTC, awni commented on mlx/ops.cpp
> +    throw std::invalid_argument("array must be atleast 2-D");
add `[tril]` to the front of the error message.

2023-12-15 03:42 UTC, awni commented on mlx/ops.cpp
> +  auto r = broadcast_to(expand_dims(arange(-k, m - k, s), 0, s), {n, m}, s);
explicit broadcasting is not needed here, `greater_equal` broadcasts its args.

2023-12-16 00:45 UTC, nullhook commented
waiting for this to be merged

2023-12-16 01:29 UTC, awni commented
Just added a few minor updates + docs. This is ready to go. Will merge as soon as the CI is done!

2023-12-16 01:30 UTC, awni approved these changes
Beautifully done, thank you!

2023-12-16 01:30 UTC, merged