numpy functions
ml-explore/mlx pull request #423
Opened 2024-01-10 21:30 UTC by ayush-1506

## Proposed changes

I wrote a few numpy functions for a personal project a while back. Creating this PR since #404 needs something similar. I'm adding only isnan for now but if this looks good, I'll go ahead and add other functions that I have.

I've added very basic CPP tests. Please let me know if it also needs python tests (in python/tests/test_ops.py).

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

2024-01-11 00:11 UTC, awni commented on mlx/ops.cpp
> +      a, full(a.shape(), std::numeric_limits<double>::quiet_NaN()), true, s);
```suggestion
  return equal(a, array(std::numeric_limits<double>::quiet_NaN(), a.dtype()), s);
```

2024-01-11 00:33 UTC, awni requested changes
Thanks for the contribution. I left a few requests in the comments. Also could you add:

- Some python tests to test the bindings?
- Produce some actual NaN and check that it works? Somehow I don't think comparing to NaN is correct in all cases as there are different representations. You can try something like:

```
mx.isnan(0 * mx.array(float("inf")))
```

- Add tests for other types (`float16`, `bfloat16`)

2024-01-11 00:33 UTC, awni commented on mlx/ops.cpp
> +      a, full(a.shape(), std::numeric_limits<double>::quiet_NaN()), true, s);
FYI isnan is supposed to return a shape that's the same size as `a`.

2024-01-11 00:33 UTC, awni commented on tests/ops_tests.cpp
> +  CHECK(all(isnan(z)).item<bool>());
Shouldn't this be false?

2024-01-11 20:30 UTC, ayush-1506 commented
@awni `mx.isnan(0 * mx.array(float("inf")))` gives me `array(true, dtype=bool)`, which is what should happen right? (comparing against numpy)

2024-01-11 20:31 UTC, awni commented
> mx.isnan(0 * mx.array(float("inf"))) gives me array(true, dtype=bool), which is what should happen right? (comparing against numpy)

Yes it should be `True`!

2024-01-12 08:14 UTC, angeloskath requested changes
I think this looks great with the tests and all!

I would, however, change the implementation to the way more common (imho) `x != x`.

2024-01-12 08:14 UTC, angeloskath commented on mlx/ops.cpp
> +array isnan(const array& a, StreamOrDevice s /* = {} */) {
I think it is much more common to simply check `not_equal(a, a, s)`

2024-01-12 15:45 UTC, ayush-1506 commented
@angeloskath Ah, thanks for pointing. Definitely seems like the more intuitive approach!

2024-01-12 18:55 UTC, awni commented on mlx/ops.cpp
> +  return a != a;
This needs to use the stream, 
```suggestion
  return not_equal(a, a, s);
```

2024-01-12 18:56 UTC, awni commented
Looks great! Could you fix my most recent comment? Then we are good to go!

2024-01-12 19:10 UTC, ayush-1506 commented
@awni Done. Just curious (trying to wrap my head around the concept of streams), if we use `!=`, is the computation going to fall back to default device (`mx.default_stream(mx.default_device())`)? Also, since the stream can be gpu, would all operators need to have a metal implementation?

2024-01-12 19:12 UTC, awni commented
> @awni Done.

Thanks!

> Just curious (trying to wrap my head around the concept of streams), if we use !=, is the computation going to fall back to default device (mx.default_stream(mx.default_device()))? 
Precisely

> Also, since the stream can be gpu, would all operators need to have a metal implementation?

Device dispatch is handled at a lower level in the stack. If you use high level ops (most of which have GPU support) then you don't need to implement anything GPU specific.

2024-01-12 19:13 UTC, awni approved these changes
🚀 thanks for the contrib!

2024-01-12 19:13 UTC, awni commented
@angeloskath needs to approve before we can merge.

2024-01-12 19:15 UTC, angeloskath approved these changes

2024-01-12 19:16 UTC, merged