[Fix] Fix SGD implementation
ml-explore/mlx pull request #473
Opened 2024-01-16 23:22 UTC by PRESIDENT810

## Proposed changes

This fixes #440 by correctly implementing SGD's weight decay and momentum. This changes includes
1. The original implementation will make weight decay not take any effect if not setting a momentum & set momentum <= 0. We should first adjust gradients regarding to weight decay then do momentum instead.
2. With dampening > 0, originally we always update `v` to `momentum * v + (1-dampening) * gradient`, but when we are in the first round of iteration where `v` is zero, we should update `v` to `gradient` instead of `(1-dampening) * gradient`.

Reference: I implemented SGD according to the algorithm described in https://pytorch.org/docs/stable/generated/torch.optim.SGD.html#sgd

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

2024-01-17 00:26 UTC, angeloskath requested changes
Hm good catch!

I think, however, that this implementation can be simplified. All we have to do is initialize `v` with `v = state.get("v", (self.dampening / self.momentum) * gradient)` and then it would be correct (including moving the momentum check as you did).

The 1st iteration will be doing some unnecessary work but I think that is completely fine. Also tbh I don't think it mattered that much that we were starting `v` with a slightly smaller gradient but still better to be correct.

2024-01-17 02:42 UTC, PRESIDENT810 commented
@angeloskath 
I tried to simplified it a little bit, but I still don't quite understand what do you mean by `v = state.get("v", (self.dampening / self.momentum) * gradient)`, especially why we have `self.dampening / self.momentum`?

Also I'm totally fine if you want me to change it back to use `(1 - self.dampening) * gradient` for the first iteration. I'm just following the algorithm displayed in that PyTorch link and don't know if that's going to make a big difference.

2024-01-17 10:21 UTC, angeloskath commented
Oh I just meant that if you initialize `v` with `(self.dampening / self.momentum) * gradient` then you don't need the check for `first_iter`. Simply put `v` should be `gradient` in the first iteration, right? So

```python
v = state.get("v", (self.dampening / self.momentum) * gradient)
if self.dampening > 0:
    v = self.momentum * v + (1-self.dampening) * gradient
```
will result in

```python
v = self.momentum * (self.dampening / self.momentum) * gradient + (1-self.dampening) * gradient
  = gradient
```

2024-01-17 10:25 UTC, angeloskath commented
In addition to the above the algorithm you implemented now is kinda wrong as it doesn't apply momentum at all when dampening is 0.

I would say the only things that needed changing were
1. moving the `if self.momentum <=0:` after the weight decay
2. initializing `v` with `(self.dampening / self.momentum) * gradient` so that the first iteration is exact

2024-01-17 21:05 UTC, PRESIDENT810 commented
Ah yes I see. I fixed it by moving momentum after weight decay and initializing `v` with default value `(self.dampening / self.momentum) * gradient` when dampening > 0. 
When dampening <= 0 I think we need to initialize v with default value 0, so we can have `v = gradient` for the first iteration.

Curious why a negative dampening value is treated as zero (although I know such a negative value doesn't make any sense).

2024-01-22 21:33 UTC, PRESIDENT810 commented
Ping

2024-01-30 23:48 UTC, angeloskath approved these changes

2024-01-30 23:50 UTC, merged