Fix package installation for CI
ml-explore/mlx pull request #521
Opened 2024-01-22 13:34 UTC by danilopeixoto

## Proposed changes

`python setup.py install` (deprecated) command is attempting to install dependencies based on remote name after building and installing the local package. We can use `python -m pip install .` instead.

https://app.circleci.com/pipelines/github/ml-explore/mlx/691/workflows/c86339cd-d578-4df6-acd3-7ce7043e83fb/jobs/1832

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

2024-01-22 18:03 UTC, awni commented
🤔 I think I'm missing something: `python setup.py install` runs fine on my machine. Do you know which command is causign it to fail?

2024-01-22 19:55 UTC, danilopeixoto commented
I don’t know exactly… But I suspect the production release works because the `python setup.py install` command finds dependencies of `mlx==0.0.10` (version set in `setup.py` for `PYPI_RELEASE=1`) in PyPi from previous upload. This does not work when the version is not in PyPi (for undefined `PYPI_RELEASE`). However, the command should not search dependencies on remote such as `python setup.py develop` or `python -m pip install .`.

2024-01-22 21:17 UTC, angeloskath commented
The failure is the check for the installation version and maybe setup tools don't support versions like `major.minor.patch.whatever` so it fails. It succeeds when `PYPI_RELEASE=1` cause then the version string is normal.

My suggestion @danilopeixoto is to change the `install` to `develop` and we 'll fix it properly when we move to `pypa/build` or something like that. The reason for develop rather than `install` in order to reuse the mlx build rather than build it twice one for install and one for `bdist_wheel`.

2024-01-22 21:18 UTC, angeloskath requested changes
Left it as a comment as well, let's change that `install` to `develop` for now and we should revisit the whole build shortly.

2024-01-25 06:01 UTC, angeloskath commented
Yeah sorry we can merge this. @danilopeixoto the comment regarding semver versioning is not exactly correct (our versioning is fine, for instance devXXX builds are even uploadable to PyPI) but I don't mind keeping it. @awni wdyt?

2024-01-25 13:48 UTC, awni commented on .circleci/config.yml
> +      # from 'development' to 'production' mode."
```suggestion
      # TODO: Modify the Python package installation command to transition
      # from 'development' to 'production' mode."
```

2024-01-25 13:49 UTC, awni commented on .circleci/config.yml
> +      # from 'development' to 'production' mode."
```suggestion
      # TODO: Update build system to switch away from setup.py develop
```

2024-01-25 13:50 UTC, awni commented
Ah I didn't notice that. Yea let's remove the bit about semantic versioning (left a suggestion in line)

2024-01-25 17:42 UTC, angeloskath approved these changes

2024-01-25 17:43 UTC, merged