mlx.core.flatten lacks dimension check
ml-explore/mlx pull request #559
Opened 2024-01-26 14:10 UTC by saurabhaloneai

issue #557

 previous code :
```
if (end_ax < start_ax) {
    throw std::invalid_argument(
        
        "start_axis must be less than or equal to end_axis");
  } ``
```

after adding the error msg : 

```
if (end_ax < start_ax) {
    throw std::invalid_argument(
        "[flatten] Invalid combination of start_axis and end_axis. "
        "start_axis must be less than or equal to end_axis");
  }
```

-----
ig it will solve the issue 
-----

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

2024-01-30 00:30 UTC, angeloskath requested changes
If we are improving the error message we might as well make available the provided `end_ax` and `start_ax` as is done in other ops. Something like `start_axis must be less... to end_axis but start_axis=N and end_axis=M`. You can use the `std::ostringstream` to create the error message.

2024-01-30 00:59 UTC, saurabhaloneai commented
Something like this right ?

```
if (start_axis >= end_axis) {
        std::ostringstream errorMessage;
        errorMessage << "Error: start_axis must be less than end_axis, but start_axis=" << start_axis << " and end_axis=" << end_axis << ".";
        
        throw std::invalid_argument(errorMessage.str());
    }
```

2024-02-02 18:59 UTC, angeloskath commented
@saurabhaloneai let me know if you 'll work on it or I can close since the current message is not that bad.

2024-02-03 00:06 UTC, saurabhaloneai commented
Thank you for your feedback. If the current message meets your expectations, I'm happy to consider the task closed :)

2024-02-03 00:21 UTC, closed without merging