Fix unsqueeze with None
ml-explore/mlx pull request #899
Opened 2024-03-25 16:08 UTC by abdussamettrkr

## Proposed changes
 Fix bug unsqueeze with None #898.

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

2024-03-25 16:33 UTC, jagrit06 requested changes

2024-03-25 16:33 UTC, jagrit06 commented on python/src/indexing.cpp
> +  }
Instead of having this as a separate loop, you can integrate it into the previous loop to check for Nones

2024-03-25 16:33 UTC, jagrit06 commented on python/src/indexing.cpp
> +    src = reshape(src, out_shape);
We can just enter the reshape loop above without the need for another branch 
What caused the bug is that is previously the expansion of ellipsis would also pad the end of the array with none slices (hence remaining indices would cover all dimensions for the src making the unsqueezed check be `remaining_indices.size() > src.ndim()`)

You can juts check if a unsqueeze is needed in the loop that prepares the slices and then enter the reshape branch above

2024-03-25 16:47 UTC, jagrit06 commented
You can just apply this quick patch! Thanks for finding the issue and working on it!
[a.patch](https://github.com/ml-explore/mlx/files/14746982/a.patch)

2024-03-25 19:23 UTC, abdussamettrkr commented
> You can just apply this quick patch! Thanks for finding the issue and working on it! [a.patch](https://github.com/ml-explore/mlx/files/14746982/a.patch)

Oh I see, thats cool.

2024-03-25 21:10 UTC, jagrit06 approved these changes
Thanks!

2024-03-25 21:46 UTC, awni commented
Could you please run the formatting hooks, looks like they failed the test

2024-03-26 13:56 UTC, awni commented
Closes #898

2024-03-26 20:59 UTC, merged